name: Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    name: Deploy modules
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Clean
      run: mvn clean
    - name: Format
      run: mvn spring-javaformat:apply
    - name: Compile
      run: mvn compile
    - name: Test
      run: mvn test